before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ocaml libev-dev

install:
  - curl -L https://github.com/OCamlPro/opam/archive/1.0.0.tar.gz | tar xz -C /tmp
  - pushd /tmp/opam-1.0.0
  - ./configure
  - make
  - sudo make install
  - popd
  - opam init -v -y
  - eval `opam config -env`
  - opam switch 4.00.1
  - eval `opam config -env`
  - opam remote add incubaid-devel -v -y -k git git://github.com/Incubaid/opam-repository-devel.git
  - opam update -v -y
  - opam install -q -v -y conf-libev lwt camlbz2 camltc.0.7.0

script:
  - eval `opam config -env`
  - ocamlbuild -use-ocamlfind -classic-display arakoon.native
# - ./arakoon.native --run-all-tests
