language: c
sudo: required

install: ./travis.sh install
script: ./travis.sh script

git:
    submodules: false

services:
  - docker

cache:
  directories:
    - ~/cache
  timeout:
    1000
before_cache: ./travis.sh before_cache
