Document: arakoon
Title: Debian arakoon Manual
Author: <insert document author here>
Abstract: This manual describes what arakoon is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/arakoon/arakoon.sgml.gz

Format: postscript
Files: /usr/share/doc/arakoon/arakoon.ps.gz

Format: text
Files: /usr/share/doc/arakoon/arakoon.text.gz

Format: HTML
Index: /usr/share/doc/arakoon/html/index.html
Files: /usr/share/doc/arakoon/html/*.html
